-- triggers - scenario 2
-- keep an audit trail, every new transaction drops a row into AuditLog
-- AuditLog isnt part of the day 5 schema so it gets created here first

CREATE TABLE AuditLog (
    LogID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    AccountID     NUMBER,
    Amount        NUMBER,
    LoggedAt      DATE
);

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (TransactionID, AccountID, Amount, LoggedAt)
    VALUES (:NEW.TransactionID, :NEW.AccountID, :NEW.Amount, SYSDATE);
END;
/
